from __future__ import annotations
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
import types as _types
from contextlib import contextmanager
import io
import threading
from contextlib import redirect_stdout, redirect_stderr


def active_project_file(instance: str) -> Path:
    return ROOT / f".active-project.{instance}"


def _write_ssl_muplugin(instance: str) -> None:
    """Drop a mu-plugin so WP trusts the proxy's TLS termination. Without it WP
    sees plain http inside the container, mismatches its https siteurl, and
    redirect-loops. mu-plugins auto-load with no activation; path is the same
    across apache/nginx/litespeed."""
    mu_dir = wp_dir(instance) / "wp-content" / "mu-plugins"
    mu_dir.mkdir(parents=True, exist_ok=True)
    (mu_dir / "00-sandbox-ssl.php").write_text(
        "<?php\n"
        "/* Sandbox: trust the reverse proxy's TLS termination. "
        "Generated by ./sb. */\n"
        "if ( ! empty( $_SERVER['HTTP_X_FORWARDED_PROTO'] )\n"
        "     && 'https' === $_SERVER['HTTP_X_FORWARDED_PROTO'] ) {\n"
        "    $_SERVER['HTTPS'] = 'on';\n"
        "}\n"
        "if ( ! empty( $_SERVER['HTTP_X_FORWARDED_HOST'] ) ) {\n"
        "    $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];\n"
        "}\n"
    )


def _write_mail_muplugin(instance: str) -> None:
    """Drop a mu-plugin so PHP mail is captured by the Mailpit container instead
    of being dropped on the floor. The official wordpress image has no working
    sendmail binary (sendmail_path points at /usr/sbin/sendmail, which is
    absent), so wp_mail() returns false and the captured-mail feature
    (mail_list/mail_get) never sees anything. On phpmailer_init we switch
    PHPMailer to SMTP and point it at the shared `mailpit` service on :1025.

    Lives in the shared runtime/wp-<instance> bind-mount, so it is visible to
    BOTH the web (`wp`) and the `wpcli` tiers — CLI-triggered mail
    (e.g. `./sb wp eval`, cron, tests) is captured too. mu-plugins auto-load
    with no activation and survive container restarts (unlike `wp config set`,
    which the entrypoint wipes). Image-agnostic; mirrors _write_ssl_muplugin."""
    mu_dir = wp_dir(instance) / "wp-content" / "mu-plugins"
    mu_dir.mkdir(parents=True, exist_ok=True)
    (mu_dir / "00-sandbox-mail.php").write_text(
        "<?php\n"
        "/* Sandbox: route all PHP mail to the Mailpit container so it can be\n"
        "   inspected via mail_list / mail_get. Generated by ./sb. */\n"
        "add_action( 'phpmailer_init', function ( $phpmailer ) {\n"
        "    $phpmailer->isSMTP();\n"
        "    $phpmailer->Host       = 'mailpit';\n"
        "    $phpmailer->Port       = 1025;\n"
        "    $phpmailer->SMTPAuth   = false;\n"
        "    $phpmailer->SMTPSecure = '';\n"
        "    $phpmailer->SMTPAutoTLS = false;\n"
        "} );\n"
        "// WP's default From is wordpress@localhost; PHPMailer rejects it as an\n"
        "// invalid address (no TLD), so wp_mail() fails before it ever reaches\n"
        "// SMTP. Give it a valid sandbox sender unless the caller set one.\n"
        "add_filter( 'wp_mail_from', function ( $from ) {\n"
        "    return ( $from && 'wordpress@localhost' !== $from )\n"
        "        ? $from : 'wordpress@sandbox.test';\n"
        "}, 1 );\n"
    )


def _php_literal(v) -> str:
    """Render a config scalar as a PHP literal for a define()."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if v is None:
        return "null"
    s = str(v).replace("\\", "\\\\").replace("'", "\\'")
    return f"'{s}'"


def _merged_wp_config(inst_cfg: dict) -> dict:
    """Sandbox defaults overlaid with the project's `config` dict (project
    wins). WP_DEBUG is excluded: the official image defines it from the
    WORDPRESS_DEBUG env var BEFORE the WORDPRESS_CONFIG_EXTRA eval, so a
    define() here would collide — see _wp_debug_env."""
    merged = {**_BASE_WP_CONFIG, **(inst_cfg.get("wp_config") or {})}
    merged.pop("WP_DEBUG", None)
    return merged


def _wp_debug_env(inst_cfg: dict) -> str:
    """WORDPRESS_DEBUG env value: WP_DEBUG defaults to true in the sandbox;
    only an explicit `"WP_DEBUG": false` in the project config turns it off."""
    return "" if (inst_cfg.get("wp_config") or {}).get("WP_DEBUG") is False else "1"


def _multisite_mode(inst_cfg: dict):
    """None (single site) | 'subdirectory' | 'subdomain'. `true` means
    subdirectory — the baseline that works on localhost:<port> with no
    wildcard DNS."""
    ms = inst_cfg.get("multisite")
    if not ms:
        return None
    return "subdomain" if str(ms).lower() == "subdomain" else "subdirectory"


def _ensure_litespeed_htaccess(inst: str) -> None:
    """Write the canonical WP rewrite .htaccess into the docroot and reload
    OpenLiteSpeed so it honors it. WordPress only writes a physical .htaccess
    under Apache — under OLS it writes none, so pretty permalinks + /wp-json/
    404 without this. The image's vhost template does `autoLoadHtaccess`, but
    only re-reads on reload. Idempotent: keeps an existing .htaccess as-is.
    Called on install AND when switching an instance to the litespeed server."""
    htaccess = wp_dir(inst) / ".htaccess"
    if not htaccess.exists():
        info("litespeed: writing WordPress .htaccess (OLS autoloads it for rewrites)…")
        htaccess.write_text(
            "# BEGIN WordPress\n"
            "<IfModule mod_rewrite.c>\n"
            "RewriteEngine On\n"
            "RewriteBase /\n"
            "RewriteRule ^index\\.php$ - [L]\n"
            "RewriteCond %{REQUEST_FILENAME} !-f\n"
            "RewriteCond %{REQUEST_FILENAME} !-d\n"
            "RewriteRule . /index.php [L]\n"
            "</IfModule>\n"
            "# END WordPress\n"
        )
    # OLS cached the vhost on boot BEFORE the .htaccess existed, so it won't
    # honor it until reloaded. Graceful reload picks it up.
    info("litespeed: reloading OpenLiteSpeed to load the new .htaccess…")
    compose("exec", "-T", "wp", "/usr/local/lsws/bin/lswsctrl", "restart",
            instance=inst, check=False)


def _pin_db_creds_in_config(inst: str) -> None:
    """Write the DB credentials as LITERAL constants into wp-config.php.

    The default wp-config resolves creds via getenv_docker('WORDPRESS_DB_*').
    That works under the official wordpress image (apache/nginx) because its
    entrypoint exports those env vars to php-fpm — but OpenLiteSpeed's lsphp
    runs via suExec and does NOT inherit the container environment, so getenv()
    returns empty and WP 500s with "Error establishing a database connection"
    the moment an instance is switched to litespeed. Pinning literal values
    makes the config server-agnostic: correct under apache, nginx, AND OLS.
    Idempotent — `wp config set` overwrites the constant in place."""
    info("pinning DB credentials into wp-config.php (server-agnostic)…")
    for const, val in (("DB_HOST", "db:3306"), ("DB_USER", "wp"),
                       ("DB_PASSWORD", "wp"), ("DB_NAME", "wp")):
        wpcli(["config", "set", const, val], instance=inst, check=False)


def _pin_wp_constants_in_config(inst: str, inst_cfg: dict) -> None:
    """litespeed: write the merged wp-config constants as LITERALS via
    `wp config set` — same rationale as _pin_db_creds_in_config: lsphp can't
    see the container env, so the WORDPRESS_CONFIG_EXTRA mechanism that
    apache/nginx use is invisible to it. The OLS image doesn't regenerate
    wp-config.php on start, so the literals persist there."""
    constants = {"WP_DEBUG": _wp_debug_env(inst_cfg) == "1",
                 **_merged_wp_config(inst_cfg)}
    # An already-converted multisite needs its network constants literal too
    # (the marker-gated block in WORDPRESS_CONFIG_EXTRA never runs under OLS).
    # On a fresh install the marker doesn't exist yet — multisite-convert
    # writes the constants into wp-config.php itself, which persists under OLS.
    mode = _multisite_mode(inst_cfg)
    if mode and (wp_dir(inst) / MULTISITE_MARKER).exists():
        constants.update({
            "WP_ALLOW_MULTISITE": True,
            "MULTISITE": True,
            "SUBDOMAIN_INSTALL": mode == "subdomain",
            "DOMAIN_CURRENT_SITE": _site_host(inst_cfg),
            "PATH_CURRENT_SITE": "/",
            "SITE_ID_CURRENT_SITE": 1,
            "BLOG_ID_CURRENT_SITE": 1,
        })
    info("pinning wp-config constants into wp-config.php (literal)…")
    for k, v in constants.items():
        if isinstance(v, str):
            wpcli(["config", "set", k, v], instance=inst, check=False)
        else:
            wpcli(["config", "set", k, _php_literal(v), "--raw"],
                  instance=inst, check=False)


def _write_multisite_htaccess(inst: str, mode: str) -> None:
    """The WP network .htaccess. WordPress never writes it itself (network
    setup only DISPLAYS the rules to paste), so without this /site2/wp-admin/
    and core assets under a subdirectory site 404. The same rules serve
    apache and OpenLiteSpeed (autoLoadHtaccess); nginx carries its equivalent
    in config/nginx-sandbox.conf."""
    strip = "" if mode == "subdomain" else "([_0-9a-zA-Z-]+/)?"
    ref = "$1" if mode == "subdomain" else "$2"
    (wp_dir(inst) / ".htaccess").write_text(
        "# BEGIN WordPress Multisite — generated by ./sb\n"
        "RewriteEngine On\n"
        "RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]\n"
        "RewriteBase /\n"
        "RewriteRule ^index\\.php$ - [L]\n"
        f"RewriteRule ^{strip}wp-admin$ {'$1' if strip else ''}wp-admin/ [R=301,L]\n"
        "RewriteCond %{REQUEST_FILENAME} -f [OR]\n"
        "RewriteCond %{REQUEST_FILENAME} -d\n"
        "RewriteRule ^ - [L]\n"
        f"RewriteRule ^{strip}(wp-(content|admin|includes).*) {ref} [L]\n"
        f"RewriteRule ^{strip}(.*\\.php)$ {ref} [L]\n"
        "RewriteRule . index.php [L]\n"
        "# END WordPress Multisite\n"
    )


def _convert_multisite(inst: str, inst_cfg: dict) -> None:
    """Convert a freshly installed single site to multisite, per the project's
    `multisite` config. Idempotent: skips the convert when the network tables
    already exist. The marker file written here is what turns on the MULTISITE
    constants in WORDPRESS_CONFIG_EXTRA (see _config_extra_php) — wp-cli also
    writes them into wp-config.php, but the official entrypoint wipes that on
    the next container start."""
    mode = _multisite_mode(inst_cfg)
    if not mode:
        return
    chk = wpcli(["core", "is-installed", "--network"],
                instance=inst, check=False, capture=True)
    if chk.returncode != 0:
        info(f"converting to multisite ({mode})…")
        cmd = ["core", "multisite-convert"]
        if mode == "subdomain":
            cmd.append("--subdomains")
        # apache/nginx get the constants from WORDPRESS_CONFIG_EXTRA (marker-
        # gated) — letting wp-cli ALSO write them into wp-config.php would
        # double-define ("already defined" warnings on every request until the
        # next restart wipes the file). litespeed/herd are the opposite: no
        # container env reaches PHP there, so the literal constants wp-cli
        # writes are the only ones that work (and their wp-config is stable).
        if inst_cfg.get("server") not in ("litespeed", "herd"):
            cmd.append("--skip-config")
        wpcli(cmd, instance=inst)
    (wp_dir(inst) / MULTISITE_MARKER).write_text(
        "Generated by ./sb after `wp core multisite-convert`. Gates the\n"
        "MULTISITE constants in WORDPRESS_CONFIG_EXTRA — delete only if you\n"
        "want the instance to fall back to single-site mode.\n")
    _write_multisite_htaccess(inst, mode)
    if inst_cfg.get("server") == "litespeed":
        # OLS only re-reads the .htaccess on reload.
        compose("exec", "-T", "wp", "/usr/local/lsws/bin/lswsctrl", "restart",
                instance=inst, check=False)


def save_local_app_password(app_pw: str, instance: str) -> None:
    """Persist the WP Application Password into sandbox.local.yml so the
    MCP server picks it up on next launch.

    Written to `instances.<name>.app_password` so each instance has its own
    secret without colliding. (Per-project model — there is no global key.)
    """
    ensure_pyyaml()
    import yaml
    local = {}
    if CONFIG_LOCAL.exists():
        with CONFIG_LOCAL.open() as f:
            local = yaml.safe_load(f) or {}
    local.setdefault("instances", {}).setdefault(instance, {})["app_password"] = app_pw
    with CONFIG_LOCAL.open("w") as f:
        yaml.safe_dump(local, f, default_flow_style=False, sort_keys=False)


def save_local_autologin_token(token: str, instance: str) -> None:
    """Persist the sandbox autologin token in sandbox.local.yml so it can be
    included in the ensure_instance return value as login_url."""
    ensure_pyyaml()
    import yaml
    local = {}
    if CONFIG_LOCAL.exists():
        with CONFIG_LOCAL.open() as f:
            local = yaml.safe_load(f) or {}
    local.setdefault("instances", {}).setdefault(instance, {})["autologin_token"] = token
    with CONFIG_LOCAL.open("w") as f:
        yaml.safe_dump(local, f, default_flow_style=False, sort_keys=False)


def _autologin_mu_plugin(token: str) -> str:
    """Render the autologin mu-plugin with the token embedded directly in the
    file. Storing the token here (not in wp-config.php) means it survives
    container restarts — the WordPress Docker entrypoint regenerates wp-config.php
    from env-vars on every start, wiping any constants we set via `wp config set`."""
    return f"""\
<?php
/**
 * Sandbox autologin — local dev only. Generated by ./sb; regenerated on recreate.
 * Visit /?sandbox_autologin=<token> to log in as admin without a password.
 * Token is in sandbox.local.yml (gitignored); never committed.
 */
// Token embedded in file so it survives wp-config.php regeneration on restart.
define( 'SANDBOX_AUTOLOGIN_TOKEN', '{token}' );

add_action( 'init', function () {{
    if ( empty( $_GET['sandbox_autologin'] ) ) {{
        return;
    }}
    if ( ! hash_equals( SANDBOX_AUTOLOGIN_TOKEN, (string) $_GET['sandbox_autologin'] ) ) {{
        return;
    }}
    $user = get_user_by( 'login', 'admin' );
    if ( $user ) {{
        wp_set_auth_cookie( $user->ID, true, is_ssl() );
        wp_safe_redirect( admin_url() );
        exit;
    }}
}}, 1 );
"""


def _force_symlink(link: Path, src: Path) -> None:
    """Replace whatever is at `link` with a symlink to `src`.

    `link.unlink()` fails with EPERM on a real (non-symlink) directory, which
    is exactly the state we hit when a wp.org install of the same slug already
    sits in the plugins folder. Detect that case and remove the directory tree
    instead. Symlinks (even dangling ones) get unlinked normally.
    """
    if link.is_symlink():
        link.unlink()
    elif link.is_dir():
        # Plain `rmtree` follows nothing here — link is a real dir, not a link.
        shutil.rmtree(link)
    elif link.exists():
        link.unlink()
    link.symlink_to(src)


def _active_project_name(instance: str) -> str | None:
    apf = active_project_file(instance)
    return apf.read_text().strip() if apf.exists() else None


def _relax_perms_for_uid_switch(inst: str) -> None:
    """Make the instance's WP files readable+writable across web-server uids.

    apache/nginx serve as www-data (uid 33); OpenLiteSpeed runs lsphp as uid
    1000. The WP files are the SAME bind-mounted host dir (runtime/wp-<inst>) —
    switching servers doesn't move data, but files written under one uid must
    stay readable (and uploads writable) under the other. The real fix for a
    bind-mounted dev tree is permissive group/other bits: a+rX everywhere, and
    a+rwX on the writable trees (uploads, cache, upgrade). No sudo, no chown —
    works whoever owns the files on the host."""
    root = wp_dir(inst)
    if not root.exists():
        return
    info(f"relaxing file perms on {root.name} so both web-server uids can read/write…")
    for p in root.rglob("*"):
        try:
            if p.is_dir():
                p.chmod(p.stat().st_mode | 0o055)        # a+rx on dirs
            else:
                p.chmod(p.stat().st_mode | 0o044)        # a+r on files
        except OSError:
            pass
    # The trees WP writes to at runtime need group/other write too.
    for sub in ("wp-content/uploads", "wp-content/cache", "wp-content/upgrade"):
        d = root / sub
        for p in [d, *d.rglob("*")] if d.exists() else []:
            try:
                p.chmod(p.stat().st_mode | (0o022 if p.is_dir() else 0o022))
            except OSError:
                pass


def _wire_project_plugins(name: str, root: str, pconf: dict) -> None:
    """Symlink the project's plugins + mappings into the instance, then activate.

    Relative mapping sources ("." or "../sibling") are resolved relative to
    root_path (the project dir), matching wp-env's convention.
    NOTE: absolute symlinks only resolve inside the container when the target is
    under a bind-mounted host path. Sources under defaults.plugins_home work
    today; a project root outside it needs its own bind mount (T0.4 follow-up)."""
    pdir = plugins_dir(name)
    pdir.mkdir(parents=True, exist_ok=True)
    root_path = Path(root)
    activate, zips, slugs = [], [], []
    for entry in pconf.get("plugins") or ["."]:
        if entry == ".":
            slug = root_path.name
            _force_symlink(pdir / slug, root_path)
            activate.append(slug)
        elif isinstance(entry, str) and entry.startswith("http") and entry.endswith(".zip"):
            zips.append(entry)
        elif isinstance(entry, str) and ("/" in entry or entry.startswith((".", "~"))):
            src = Path(entry).expanduser()
            if not src.is_absolute():
                src = (root_path / entry).resolve()
            if src.exists():
                _force_symlink(pdir / src.name, src)
                activate.append(src.name)
        elif entry:
            slugs.append(entry)
    wp_root = wp_dir(name)
    map_activate: list[str] = []
    for wp_path, src in (pconf.get("mappings") or {}).items():
        src_p = Path(str(src)).expanduser()
        if not src_p.is_absolute():
            src_p = (root_path / src_p).resolve()
        if src_p.exists():
            dest = wp_root / wp_path
            dest.parent.mkdir(parents=True, exist_ok=True)
            _force_symlink(dest, src_p)
            # Activate if this is a plugin mapping (wp-content/plugins/<slug>).
            parts = wp_path.strip("/").split("/")
            if len(parts) == 3 and parts[0] == "wp-content" and parts[1] == "plugins":
                map_activate.append(parts[2])
    # mappings_inactive: mount the symlink but do NOT activate.
    for wp_path, src in (pconf.get("mappings_inactive") or {}).items():
        src_p = Path(str(src)).expanduser()
        if not src_p.is_absolute():
            src_p = (root_path / src_p).resolve()
        if src_p.exists():
            dest = wp_root / wp_path
            dest.parent.mkdir(parents=True, exist_ok=True)
            _force_symlink(dest, src_p)
    # Install only what isn't already present; reinstalling an existing plugin
    # just emits "Plugin already installed." noise. Already-present ones still
    # get activated (install --activate only activates the freshly installed).
    install, reactivate = [], []
    for entry in zips + slugs:
        (reactivate if (pdir / _pkg_slug(entry)).exists() else install).append(entry)
    if install:
        wpcli(["plugin", "install", *install, "--activate"],
              instance=name, check=False)
    if reactivate:
        wpcli(["plugin", "activate", *[_pkg_slug(e) for e in reactivate]],
              instance=name, check=False)
    if activate:
        wpcli(["plugin", "activate", *activate], instance=name, check=False)
    if map_activate:
        wpcli(["plugin", "activate", *map_activate], instance=name, check=False)


def _pkg_slug(entry: str) -> str:
    """Best-effort slug from a plugin/theme entry: wp.org slug as-is; zip URL by
    basename minus the version tail (twentytwentyfour.1.5.zip →
    twentytwentyfour); local path by directory name."""
    if entry.startswith("http"):
        base = entry.rstrip("/").rsplit("/", 1)[-1]
        base = base[:-4] if base.endswith(".zip") else base
        return re.sub(r"\.\d[\d.]*$", "", base)
    if "/" in entry or entry.startswith((".", "~")):
        return Path(entry).expanduser().name
    return entry


def _wire_project_themes(name: str, root: str, pconf: dict) -> None:
    """Install the project's `themes` and activate the FIRST one. Same entry
    forms as plugins: wp.org slug, zip URL, or local path (symlinked in —
    needs an extra_mounts bind like plugin paths do). Activation is a
    separate explicit step: `theme install --activate` is silently ignored
    on multisite installs."""
    themes = [t for t in (pconf.get("themes") or []) if t and isinstance(t, str)]
    if not themes:
        return
    tdir = wp_dir(name) / "wp-content" / "themes"
    tdir.mkdir(parents=True, exist_ok=True)
    root_path = Path(root)
    for entry in themes:
        if entry.startswith("http") and entry.endswith(".zip"):
            if (tdir / _pkg_slug(entry)).exists():
                continue  # already present (bundled / prior provision) — skip noisy reinstall
            wpcli(["theme", "install", entry], instance=name, check=False)
        elif "/" in entry or entry.startswith((".", "~")):
            src = Path(entry).expanduser()
            if not src.is_absolute():
                src = (root_path / entry).resolve()
            if src.exists():
                _force_symlink(tdir / src.name, src)
        elif (tdir / _pkg_slug(entry)).exists():
            # Already present (e.g. a default theme bundled with WP core, or a
            # prior provision). Reinstalling only emits "Destination folder
            # already exists" + "Error: No themes installed." noise — skip it.
            continue
        else:
            wpcli(["theme", "install", entry], instance=name, check=False)
    wpcli(["theme", "activate", _pkg_slug(themes[0])],
          instance=name, check=False)
