from __future__ import annotations
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
import types as _types
from contextlib import contextmanager
import io
import threading
from contextlib import redirect_stdout, redirect_stderr


def active_project_file(instance: str) -> Path:
    return ROOT / f".active-project.{instance}"


def _ensure_muplugins_dir(instance: str) -> Path:
    """Create wp-content/mu-plugins, repairing Docker-created host ownership
    when needed.

    On a fresh remote VPS the official WordPress image can create the bind
    mount as www-data:www-data before host-side `sb` writes its sandbox
    mu-plugins. Local dev machines usually don't need privilege repair, so
    only try `sudo -n chown` after the normal mkdir path fails."""
    mu_dir = wp_dir(instance) / "wp-content" / "mu-plugins"
    try:
        mu_dir.mkdir(parents=True, exist_ok=True)
        return mu_dir
    except PermissionError:
        root = wp_dir(instance)
        res = subprocess.run(
            ["sudo", "-n", "chown", "-R", f"{os.getuid()}:{os.getgid()}", str(root)],
            capture_output=True, text=True, timeout=60, check=False,
        )
        if res.returncode != 0:
            raise PermissionError(
                f"cannot write sandbox mu-plugins under {root}; tried normal mkdir "
                f"and sudo -n chown, but chown failed: "
                f"{(res.stderr or res.stdout or '').strip()[:500]}"
            )
        for p in [root, *root.rglob("*")]:
            try:
                if p.is_dir():
                    p.chmod(p.stat().st_mode | 0o055)
                else:
                    p.chmod(p.stat().st_mode | 0o044)
            except OSError:
                pass
        for sub in ("wp-content/uploads", "wp-content/cache", "wp-content/upgrade"):
            d = root / sub
            d.mkdir(parents=True, exist_ok=True)
            for p in [d, *d.rglob("*")]:
                try:
                    p.chmod(p.stat().st_mode | 0o022)
                except OSError:
                    pass
        mu_dir.mkdir(parents=True, exist_ok=True)
        return mu_dir


def _write_ssl_muplugin(instance: str) -> None:
    """Drop a mu-plugin so WP trusts the proxy's TLS termination. Without it WP
    sees plain http inside the container, mismatches its https siteurl, and
    redirect-loops. mu-plugins auto-load with no activation; path is the same
    across apache/nginx/litespeed."""
    mu_dir = _ensure_muplugins_dir(instance)
    (mu_dir / "00-sandbox-ssl.php").write_text(
        "<?php\n"
        "/* Sandbox: trust the reverse proxy's TLS termination. "
        "Generated by ./sb. */\n"
        "if ( ! empty( $_SERVER['HTTP_X_FORWARDED_PROTO'] )\n"
        "     && 'https' === $_SERVER['HTTP_X_FORWARDED_PROTO'] ) {\n"
        "    $_SERVER['HTTPS'] = 'on';\n"
        "}\n"
        "if ( ! empty( $_SERVER['HTTP_X_FORWARDED_HOST'] ) ) {\n"
        "    $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];\n"
        "}\n"
    )


def _write_mail_muplugin(instance: str) -> None:
    """Drop a mu-plugin so PHP mail is captured by the Mailpit container instead
    of being dropped on the floor. The official wordpress image has no working
    sendmail binary (sendmail_path points at /usr/sbin/sendmail, which is
    absent), so wp_mail() returns false and the captured-mail feature
    (mail_list/mail_get) never sees anything. On phpmailer_init we switch
    PHPMailer to SMTP and point it at the shared `mailpit` service on :1025.

    Lives in the shared runtime/wp-<instance> bind-mount, so it is visible to
    BOTH the web (`wp`) and the `wpcli` tiers — CLI-triggered mail
    (e.g. `./sb wp eval`, cron, tests) is captured too. mu-plugins auto-load
    with no activation and survive container restarts (unlike `wp config set`,
    which the entrypoint wipes). Image-agnostic; mirrors _write_ssl_muplugin."""
    mu_dir = _ensure_muplugins_dir(instance)
    (mu_dir / "00-sandbox-mail.php").write_text(
        "<?php\n"
        "/* Sandbox: route all PHP mail to the Mailpit container so it can be\n"
        "   inspected via mail_list / mail_get. Generated by ./sb. */\n"
        "add_action( 'phpmailer_init', function ( $phpmailer ) {\n"
        "    $phpmailer->isSMTP();\n"
        "    $phpmailer->Host       = 'mailpit';\n"
        "    $phpmailer->Port       = 1025;\n"
        "    $phpmailer->SMTPAuth   = false;\n"
        "    $phpmailer->SMTPSecure = '';\n"
        "    $phpmailer->SMTPAutoTLS = false;\n"
        "} );\n"
        "// WP's default From is wordpress@localhost; PHPMailer rejects it as an\n"
        "// invalid address (no TLD), so wp_mail() fails before it ever reaches\n"
        "// SMTP. Give it a valid sandbox sender unless the caller set one.\n"
        "add_filter( 'wp_mail_from', function ( $from ) {\n"
        "    return ( $from && 'wordpress@localhost' !== $from )\n"
        "        ? $from : 'wordpress@sandbox.test';\n"
        "}, 1 );\n"
    )


def _write_debug_muplugins(instance: str) -> None:
    """Drop the dump()/dd() + Query Monitor capture mu-plugins (spec 007).

    Host-file based (works on Docker AND herd). dump() writes to
    wp-content/debug-dump.log; the QM capture writes wp-content/qm.jsonl on
    shutdown. Copied from sandbox/assets/dump/. Idempotent; both self-gate."""
    asset = Path(__file__).resolve().parent.parent / "assets" / "dump"
    mu_dir = _ensure_muplugins_dir(instance)
    for fn in ("00-sandbox-dump.php", "00-sandbox-qm.php"):
        src = asset / fn
        if src.exists():
            shutil.copyfile(src, mu_dir / fn)


def _write_abilities_muplugin(instance: str) -> None:
    """Drop the Sandbox Abilities mu-plugin (spec 003) into the instance.

    Registers `sandbox/*` abilities on the WP 6.9+ Abilities API so AI agents can
    run code / manage files in the live runtime. Copied from the maintained asset
    `sandbox/assets/abilities/00-sandbox-abilities.php` (a real, lintable PHP file)
    rather than an inline string. Host-file based, so it works on Docker AND herd.
    Idempotent; the mu-plugin self-gates on the Abilities API + an enable flag, so
    it no-ops on older WP. Mirrors _write_mail_muplugin."""
    asset_dir = Path(__file__).resolve().parent.parent / "assets" / "abilities"
    src = asset_dir / "00-sandbox-abilities.php"
    if not src.exists():
        return
    mu_dir = wp_dir(instance) / "wp-content" / "mu-plugins"
    mu_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, mu_dir / "00-sandbox-abilities.php")
    # Copy the payload dir (vendored wordpress/mcp-adapter) that the loader
    # require_once's for the MCP-server exposure. Refresh in place each call.
    payload = asset_dir / "sandbox-abilities"
    if payload.is_dir():
        dest = mu_dir / "sandbox-abilities"
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(payload, dest)


_ONDEMAND_MU_TEMPLATE = r'''<?php
/**
 * Sandbox On-Demand Plugins (spec 010) — local dev only. Generated by ./sb.
 *
 * Slugs declared on-demand (or locally-sourced) in the sandbox config are listed
 * in sandbox-local-sources.json (slug -> {path|zip}). On any install attempt of
 * such a slug — Templately Full Site Import, wp-cli `plugin install`, or the
 * wp-admin "Add Plugin" flow — we serve the LOCAL copy instead of downloading:
 *   - plugins_api: make the slug "known" with a sentinel download_link.
 *   - upgrader_pre_download: swap the sentinel/slug for a THROWAWAY temp zip built
 *     from the local source (WP deletes the package it is handed — never the real
 *     source). Mirrors the dl-cache temp-copy rule.
 * Plus a Plugins-screen page listing on-demand plugins with one-click install.
 */
if ( ! defined( 'ABSPATH' ) ) { return; }

function sandbox_ondemand_map() {
	static $map = null;
	if ( null !== $map ) { return $map; }
	$map = array();
	$f = __DIR__ . '/sandbox-local-sources.json';
	if ( is_readable( $f ) ) {
		$d = json_decode( (string) file_get_contents( $f ), true );
		if ( is_array( $d ) ) { $map = $d; }
	}
	return $map;
}

/** Slug from a package URL/sentinel, or '' if not one of ours. */
function sandbox_ondemand_slug_for( $package ) {
	if ( ! is_string( $package ) || '' === $package ) { return ''; }
	if ( 0 === strpos( $package, 'sandbox-ondemand://' ) ) {
		return substr( $package, strlen( 'sandbox-ondemand://' ) );
	}
	// wp.org URL → slug (downloads.wordpress.org/plugin/<slug>.<ver>.zip)
	if ( preg_match( '#/plugin/([^/]+?)(\.\d[\d.]*)?\.zip#', $package, $m ) ) {
		$slug = $m[1];
		$map = sandbox_ondemand_map();
		if ( isset( $map[ $slug ] ) ) { return $slug; }
	}
	return '';
}

/** Build a throwaway temp zip for a slug's local source, or WP_Error. */
function sandbox_ondemand_local_zip( $slug ) {
	$map = sandbox_ondemand_map();
	if ( empty( $map[ $slug ] ) ) {
		return new WP_Error( 'sandbox_ondemand', "No local source for '$slug'." );
	}
	$entry = $map[ $slug ];
	if ( ! empty( $entry['zip'] ) ) {
		if ( ! is_readable( $entry['zip'] ) ) {
			return new WP_Error( 'sandbox_ondemand', "Local zip missing: {$entry['zip']}" );
		}
		$tmp = wp_tempnam( $slug . '.zip' );
		if ( ! @copy( $entry['zip'], $tmp ) ) {
			return new WP_Error( 'sandbox_ondemand', 'Could not copy local zip.' );
		}
		return $tmp;
	}
	$dir = isset( $entry['path'] ) ? $entry['path'] : '';
	if ( ! $dir || ! is_dir( $dir ) ) {
		return new WP_Error( 'sandbox_ondemand', "Local source dir missing: $dir" );
	}
	if ( ! class_exists( 'ZipArchive' ) ) {
		return new WP_Error( 'sandbox_ondemand', 'ZipArchive unavailable.' );
	}
	$tmp = wp_tempnam( $slug . '.zip' );
	$zip = new ZipArchive();
	if ( true !== $zip->open( $tmp, ZipArchive::CREATE | ZipArchive::OVERWRITE ) ) {
		return new WP_Error( 'sandbox_ondemand', 'Could not create temp zip.' );
	}
	$base = rtrim( $dir, '/' );
	$it = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator( $base, FilesystemIterator::SKIP_DOTS ),
		RecursiveIteratorIterator::SELF_FIRST );
	foreach ( $it as $file ) {
		$path = $file->getPathname();
		$rel  = $slug . '/' . ltrim( substr( $path, strlen( $base ) ), '/' );
		if ( $file->isDir() ) { $zip->addEmptyDir( $rel ); }
		else { $zip->addFile( $path, $rel ); }
	}
	$zip->close();
	return $tmp;
}

// Make on-demand slugs resolvable by the installer (wp-cli / wp-admin by slug).
add_filter( 'plugins_api', function ( $res, $action, $args ) {
	if ( 'plugin_information' !== $action || empty( $args->slug ) ) { return $res; }
	$map = sandbox_ondemand_map();
	if ( empty( $map[ $args->slug ] ) ) { return $res; }
	$slug = $args->slug;
	return (object) array(
		'name'          => $slug,
		'slug'          => $slug,
		'version'       => 'local',
		'download_link' => 'sandbox-ondemand://' . $slug,
		'sections'      => array( 'description' => 'Sandbox on-demand (local source).' ),
	);
}, 10, 3 );

// Serve the local copy for our sentinel / matched slug (throwaway temp zip).
add_filter( 'upgrader_pre_download', function ( $reply, $package, $upgrader ) {
	$slug = sandbox_ondemand_slug_for( $package );
	if ( '' === $slug ) { return $reply; }
	$zip = sandbox_ondemand_local_zip( $slug );
	return is_wp_error( $zip ) ? $zip : $zip;
}, 5, 3 );

// --- Admin: list on-demand plugins + one-click install-from-local -----------
add_action( 'admin_menu', function () {
	add_plugins_page(
		'Sandbox: On-Demand', 'Sandbox On-Demand',
		'manage_options', 'sandbox-ondemand', 'sandbox_ondemand_render' );
} );

function sandbox_ondemand_render() {
	if ( ! current_user_can( 'manage_options' ) ) { return; }
	if ( isset( $_POST['sandbox_ondemand_install'] ) ) {
		check_admin_referer( 'sandbox_ondemand' );
		$slug = isset( $_POST['slug'] ) ? sanitize_key( wp_unslash( $_POST['slug'] ) ) : '';
		require_once ABSPATH . 'wp-admin/includes/class-wp-upgrader.php';
		require_once ABSPATH . 'wp-admin/includes/plugin-install.php';
		$up  = new Plugin_Upgrader( new Automatic_Upgrader_Skin() );
		$res = $up->install( 'sandbox-ondemand://' . $slug );
		echo '<div class="notice notice-' . ( is_wp_error( $res ) || ! $res ? 'error' : 'success' ) .
			'"><p>' . esc_html( is_wp_error( $res ) ? $res->get_error_message() :
			( $res ? "Installed '$slug' from local." : "Install of '$slug' failed." ) ) . '</p></div>';
	}
	$map = sandbox_ondemand_map();
	echo '<div class="wrap"><h1>Sandbox: On-Demand Plugins</h1>';
	echo '<p>Declared with a local source; installed from your local copy on demand (no download).</p>';
	if ( empty( $map ) ) { echo '<p>None declared.</p></div>'; return; }
	echo '<table class="widefat striped"><thead><tr><th>Plugin</th><th>Source</th><th>State</th><th></th></tr></thead><tbody>';
	foreach ( $map as $slug => $entry ) {
		$src = isset( $entry['zip'] ) ? $entry['zip'] : ( isset( $entry['path'] ) ? $entry['path'] : '?' );
		$installed = file_exists( WP_PLUGIN_DIR . '/' . $slug );
		echo '<tr><td><strong>' . esc_html( $slug ) . '</strong></td><td><code>' . esc_html( $src ) . '</code></td><td>' .
			( $installed ? 'installed' : 'available' ) . '</td><td>';
		if ( ! $installed ) {
			echo '<form method="post" style="margin:0">';
			wp_nonce_field( 'sandbox_ondemand' );
			echo '<input type="hidden" name="slug" value="' . esc_attr( $slug ) . '">';
			echo '<button class="button button-primary" name="sandbox_ondemand_install" value="1">Install from local</button>';
			echo '</form>';
		}
		echo '</td></tr>';
	}
	echo '</tbody></table></div>';
}
'''


_DL_CACHE_MU_TEMPLATE = r'''<?php
/* Sandbox: cache plugin/theme zip downloads (Templately Full Site Import
   especially) so WP-runtime installs reuse a cached zip instead of
   re-downloading. Templately FSI installs deps via Plugin_Upgrader->install(
   $download_link ), which fires WP's upgrader_pre_download filter — we hook it.

   Cache key is the (version-specific) download URL. Freshness is enforced by an
   HTTP conditional revalidation (ETag / Last-Modified): we only ask upstream
   "is there a newer build?" once the throttle window (SANDBOX_DL_CACHE_TTL,
   default 12h) has elapsed; a 304 keeps the cached zip, a 200 replaces it.
   Within the window the cache is served with NO upstream call at all.

   WP_Upgrader deletes the package file we return (it treats it as a throwaway
   download temp), so we always hand back a temp COPY and keep the cache file.
   The cache dir is the shared host mount runtime/dl-cache/wp-http →
   /sandbox-dl-cache (web tier only; on wpcli the guard bails and `wp install`
   uses WP_CLI_CACHE_DIR, which is itself version-keyed). Generated by ./sb. */
if ( ! defined( 'SANDBOX_DL_CACHE_DIR' ) ) {
    define( 'SANDBOX_DL_CACHE_DIR', '/sandbox-dl-cache' );
}
add_filter( 'upgrader_pre_download', function ( $reply, $package, $upgrader ) {
    if ( false !== $reply ) { return $reply; }
    if ( ! is_string( $package ) || ! preg_match( '#^https?://#i', $package ) ) {
        return $reply;
    }
    $dir = SANDBOX_DL_CACHE_DIR;
    if ( ! is_dir( $dir ) || ! is_writable( $dir ) ) { return $reply; }
    if ( ! function_exists( 'wp_tempnam' ) ) {
        require_once ABSPATH . 'wp-admin/includes/file.php';
    }

    $key   = $dir . '/' . sha1( $package );
    $zip   = $key . '.zip';
    $metaf = $key . '.json';
    $tmpf  = $key . '.tmp.' . getmypid();
    $now   = time();
    $ttl   = defined( 'SANDBOX_DL_CACHE_TTL' ) ? (int) SANDBOX_DL_CACHE_TTL : 43200;

    // Hand WP a throwaway temp COPY so its post-unpack delete can't remove our
    // cached file. Returns false if the copy fails (caller then falls through).
    $serve = function () use ( $zip, $package ) {
        $t = wp_tempnam( $package );
        return ( $t && @copy( $zip, $t ) ) ? $t : false;
    };

    clearstatcache( true, $zip );
    $have = is_file( $zip ) && filesize( $zip ) > 0;
    $meta = $have ? ( @json_decode( (string) @file_get_contents( $metaf ), true ) ?: array() ) : array();

    // Inside the throttle window: trust the cache, no upstream call (cache HIT).
    if ( $have && ( $now - (int) ( isset( $meta['checked'] ) ? $meta['checked'] : 0 ) ) < $ttl ) {
        $s = $serve();
        if ( $s ) { return $s; }
    }

    // Throttle elapsed (or cache MISS): ask upstream. Conditional GET when we
    // already hold a copy — 304 = no newer version, 200 = a newer build.
    $cond = array();
    if ( $have ) {
        if ( ! empty( $meta['etag'] ) )          { $cond['If-None-Match']     = $meta['etag']; }
        if ( ! empty( $meta['last_modified'] ) ) { $cond['If-Modified-Since'] = $meta['last_modified']; }
    }
    $resp = wp_remote_get( $package, array(
        'headers'     => $cond,
        'timeout'     => 300,
        'redirection' => 5,
        'stream'      => true,
        'filename'    => $tmpf,   // stream to disk: no large zip held in memory
    ) );
    if ( is_wp_error( $resp ) ) {
        @unlink( $tmpf );
        if ( $have ) { $s = $serve(); if ( $s ) { return $s; } }  // offline: serve stale
        return $reply;
    }
    $code = (int) wp_remote_retrieve_response_code( $resp );
    if ( 304 === $code && $have ) {
        @unlink( $tmpf );
        $meta['checked'] = $now;                                  // reset the throttle clock
        @file_put_contents( $metaf, wp_json_encode( $meta ) );
        $s = $serve(); if ( $s ) { return $s; }
        return $reply;
    }
    clearstatcache( true, $tmpf );
    if ( 200 === $code && is_file( $tmpf ) && filesize( $tmpf ) > 0 ) {
        @rename( $tmpf, $zip );                                   // same dir ⇒ atomic swap
        @file_put_contents( $metaf, wp_json_encode( array(
            'url'           => $package,
            'etag'          => wp_remote_retrieve_header( $resp, 'etag' ),
            'last_modified' => wp_remote_retrieve_header( $resp, 'last-modified' ),
            'checked'       => $now,
            'size'          => filesize( $zip ),
        ) ) );
        $s = $serve(); if ( $s ) { return $s; }
    }
    @unlink( $tmpf );
    if ( $have ) { $s = $serve(); if ( $s ) { return $s; } }      // odd status: serve stale
    return $reply;                                                // give up → WP's own path
}, 5, 3 );
'''


def _write_local_sources(instance: str, sources: dict) -> None:
    """Write the per-instance local-source map (slug -> {path|zip}) that the
    on-demand mu-plugin reads to serve local copies on install (spec 010). Host
    paths only (no secrets); the sources are bind-mounted at the same absolute
    path so the container resolves them. Always written (even empty) so a removed
    entry is cleared. Idempotent."""
    mu_dir = wp_dir(instance) / "wp-content" / "mu-plugins"
    mu_dir.mkdir(parents=True, exist_ok=True)
    (mu_dir / "sandbox-local-sources.json").write_text(
        json.dumps(sources or {}, indent=2))


def _write_ondemand_muplugin(instance: str) -> None:
    """Drop the on-demand mu-plugin (spec 010): serves LOCAL copies of slugs in
    sandbox-local-sources.json on any install attempt (FSI / wp-cli / wp-admin)
    via plugins_api + upgrader_pre_download, and adds a wp-admin page listing
    on-demand plugins with one-click 'Install from local'. Static template; reads
    the JSON map at runtime. Mirrors _write_dl_cache_muplugin."""
    mu_dir = wp_dir(instance) / "wp-content" / "mu-plugins"
    mu_dir.mkdir(parents=True, exist_ok=True)
    (mu_dir / "00-sandbox-ondemand.php").write_text(_ONDEMAND_MU_TEMPLATE)


def _write_licensing_state(instance: str) -> None:
    """Write the per-instance Pro-license state file `sandbox-licensing.json` from
    the central key store (spec 013). Carries the keys + the Elementor primary URL +
    whether THIS instance is the primary, for the modular licensing mu-plugin to read
    at runtime. ALWAYS written (even empty) so a cleared key reverts behavior.
    Secrets live only in this gitignored runtime file (like the snapshot bridge token)
    — never committed/echoed. Idempotent."""
    mu_dir = wp_dir(instance) / "wp-content" / "mu-plugins"
    mu_dir.mkdir(parents=True, exist_ok=True)
    # WPDeveloper needs no key — its platform module force-activates keylessly.
    # Elementor: carry the captured primary activation (key + license-data + URL)
    # so secondary instances ride the one connected activation.
    cap = elementor_capture()
    state = {}
    if cap.get("key"):
        state["elementor_pro_key"] = cap["key"]
        state["elementor_primary_url"] = cap.get("url")
        state["is_primary"] = (cap.get("instance") == instance)
        if cap.get("data") is not None:
            state["elementor_license_data"] = cap["data"]
    (mu_dir / "sandbox-licensing.json").write_text(json.dumps(state, indent=2))
    try:
        # PHP inside the container must be able to read this host-written file.
        # Secrets still stay in gitignored runtime state and are never echoed.
        (mu_dir / "sandbox-licensing.json").chmod(0o644)
    except OSError:
        pass


def _write_licensing_muplugin(instance: str) -> None:
    """Drop the modular Pro-license activation mu-plugin (spec 013): a loader
    (00-sandbox-licensing.php) + one file per platform under
    sandbox-licensing/platforms/. The loader reads sandbox-licensing.json and
    includes each platform module, which self-gates on its key. Copied from the
    maintained assets (real, lintable PHP). No key → no-op (additive). Mirrors
    _write_abilities_muplugin (dir-copy)."""
    asset_dir = Path(__file__).resolve().parent.parent / "assets" / "licensing"
    loader = asset_dir / "00-sandbox-licensing.php"
    if not loader.exists():
        return
    mu_dir = wp_dir(instance) / "wp-content" / "mu-plugins"
    mu_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(loader, mu_dir / "00-sandbox-licensing.php")
    platforms = asset_dir / "platforms"
    if platforms.is_dir():
        dest = mu_dir / "sandbox-licensing" / "platforms"
        if dest.parent.exists():
            shutil.rmtree(dest.parent)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(platforms, dest)
    _write_licensing_state(instance)


def _remove_obsolete_builder_authoring_assets(instance: str) -> None:
    """Remove generated builder-authoring MU-plugin assets retired from Sandbox.

    This only touches files previously generated by Sandbox; it never alters
    authored posts, pages, or installed plugins.
    """
    mu_dir = wp_dir(instance) / "wp-content" / "mu-plugins"
    for name in (
        "sandbox-editor.php",
        "00-sandbox-eb-finalizer.php",
        "00-sandbox-schema-dump.php",
        "00-sandbox-editor-schema-rest.php",
        "editor-schema-api.md",
    ):
        (mu_dir / name).unlink(missing_ok=True)
    shutil.rmtree(mu_dir / "sandbox-schema-catalog", ignore_errors=True)


def _write_dl_cache_muplugin(instance: str) -> None:
    """Drop a mu-plugin that caches plugin/theme zip downloads, so WP-runtime
    installs reuse a cached zip instead of re-downloading. The headline win is
    Templately Full Site Import, whose dependency installer calls
    `Plugin_Upgrader->install( $download_link )` → fires WP's
    `upgrader_pre_download` filter (the interception point).

    Cache is keyed by the version-specific download URL and kept fresh via an
    HTTP conditional revalidation (ETag/Last-Modified) that only fires once per
    throttle window (SANDBOX_DL_CACHE_TTL, default 12h) — see the template. The
    cache dir is the shared host mount /sandbox-dl-cache (web tier only; wpcli
    falls back to its own version-keyed WP_CLI_CACHE_DIR). Mirrors
    _write_mail_muplugin; image-agnostic; survives restarts."""
    mu_dir = wp_dir(instance) / "wp-content" / "mu-plugins"
    mu_dir.mkdir(parents=True, exist_ok=True)
    (mu_dir / "00-sandbox-dl-cache.php").write_text(_DL_CACHE_MU_TEMPLATE)


def _php_literal(v) -> str:
    """Render a config scalar as a PHP literal for a define()."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if v is None:
        return "null"
    s = str(v).replace("\\", "\\\\").replace("'", "\\'")
    return f"'{s}'"


def _merged_wp_config(inst_cfg: dict) -> dict:
    """Sandbox defaults overlaid with the project's `config` dict (project
    wins). WP_DEBUG is excluded: the official image defines it from the
    WORDPRESS_DEBUG env var BEFORE the WORDPRESS_CONFIG_EXTRA eval, so a
    define() here would collide — see _wp_debug_env."""
    merged = {**_BASE_WP_CONFIG, **(inst_cfg.get("wp_config") or {})}
    merged.pop("WP_DEBUG", None)
    return merged


def _wp_debug_env(inst_cfg: dict) -> str:
    """WORDPRESS_DEBUG env value: WP_DEBUG defaults to true in the sandbox;
    only an explicit `"WP_DEBUG": false` in the project config turns it off."""
    return "" if (inst_cfg.get("wp_config") or {}).get("WP_DEBUG") is False else "1"


def _multisite_mode(inst_cfg: dict):
    """None (single site) | 'subdirectory' | 'subdomain'. `true` means
    subdirectory — the baseline that works on localhost:<port> with no
    wildcard DNS."""
    ms = inst_cfg.get("multisite")
    if not ms:
        return None
    return "subdomain" if str(ms).lower() == "subdomain" else "subdirectory"


def _ensure_litespeed_htaccess(inst: str) -> None:
    """Write the canonical WP rewrite .htaccess into the docroot and reload
    OpenLiteSpeed so it honors it. WordPress only writes a physical .htaccess
    under Apache — under OLS it writes none, so pretty permalinks + /wp-json/
    404 without this. The image's vhost template does `autoLoadHtaccess`, but
    only re-reads on reload. Idempotent: keeps an existing .htaccess as-is.
    Called on install AND when switching an instance to the litespeed server."""
    htaccess = wp_dir(inst) / ".htaccess"
    if not htaccess.exists():
        info("litespeed: writing WordPress .htaccess (OLS autoloads it for rewrites)…")
        htaccess.write_text(
            "# BEGIN WordPress\n"
            "<IfModule mod_rewrite.c>\n"
            "RewriteEngine On\n"
            "RewriteBase /\n"
            "RewriteRule ^index\\.php$ - [L]\n"
            "RewriteCond %{REQUEST_FILENAME} !-f\n"
            "RewriteCond %{REQUEST_FILENAME} !-d\n"
            "RewriteRule . /index.php [L]\n"
            "</IfModule>\n"
            "# END WordPress\n"
        )
    # OLS cached the vhost on boot BEFORE the .htaccess existed, so it won't
    # honor it until reloaded. Graceful reload picks it up.
    info("litespeed: reloading OpenLiteSpeed to load the new .htaccess…")
    compose("exec", "-T", "wp", "/usr/local/lsws/bin/lswsctrl", "restart",
            instance=inst, check=False)


def _pin_db_creds_in_config(inst: str) -> None:
    """Write the DB credentials as LITERAL constants into wp-config.php.

    The default wp-config resolves creds via getenv_docker('WORDPRESS_DB_*').
    That works under the official wordpress image (apache/nginx) because its
    entrypoint exports those env vars to php-fpm — but OpenLiteSpeed's lsphp
    runs via suExec and does NOT inherit the container environment, so getenv()
    returns empty and WP 500s with "Error establishing a database connection"
    the moment an instance is switched to litespeed. Pinning literal values
    makes the config server-agnostic: correct under apache, nginx, AND OLS.
    Idempotent — `wp config set` overwrites the constant in place."""
    info("pinning DB credentials into wp-config.php (server-agnostic)…")
    for const, val in (("DB_HOST", "db:3306"), ("DB_USER", "wp"),
                       ("DB_PASSWORD", "wp"), ("DB_NAME", "wp")):
        wpcli(["config", "set", const, val], instance=inst, check=False)


def _pin_wp_constants_in_config(inst: str, inst_cfg: dict) -> None:
    """litespeed: write the merged wp-config constants as LITERALS via
    `wp config set` — same rationale as _pin_db_creds_in_config: lsphp can't
    see the container env, so the WORDPRESS_CONFIG_EXTRA mechanism that
    apache/nginx use is invisible to it. The OLS image doesn't regenerate
    wp-config.php on start, so the literals persist there."""
    constants = {"WP_DEBUG": _wp_debug_env(inst_cfg) == "1",
                 **_merged_wp_config(inst_cfg)}
    # An already-converted multisite needs its network constants literal too
    # (the marker-gated block in WORDPRESS_CONFIG_EXTRA never runs under OLS).
    # On a fresh install the marker doesn't exist yet — multisite-convert
    # writes the constants into wp-config.php itself, which persists under OLS.
    mode = _multisite_mode(inst_cfg)
    if mode and (wp_dir(inst) / MULTISITE_MARKER).exists():
        constants.update({
            "WP_ALLOW_MULTISITE": True,
            "MULTISITE": True,
            "SUBDOMAIN_INSTALL": mode == "subdomain",
            "DOMAIN_CURRENT_SITE": _site_host(inst_cfg),
            "PATH_CURRENT_SITE": "/",
            "SITE_ID_CURRENT_SITE": 1,
            "BLOG_ID_CURRENT_SITE": 1,
        })
    info("pinning wp-config constants into wp-config.php (literal)…")
    for k, v in constants.items():
        if isinstance(v, str):
            wpcli(["config", "set", k, v], instance=inst, check=False)
        else:
            wpcli(["config", "set", k, _php_literal(v), "--raw"],
                  instance=inst, check=False)


def _write_multisite_htaccess(inst: str, mode: str) -> None:
    """The WP network .htaccess. WordPress never writes it itself (network
    setup only DISPLAYS the rules to paste), so without this /site2/wp-admin/
    and core assets under a subdirectory site 404. The same rules serve
    apache and OpenLiteSpeed (autoLoadHtaccess); nginx carries its equivalent
    in config/nginx-sandbox.conf."""
    strip = "" if mode == "subdomain" else "([_0-9a-zA-Z-]+/)?"
    ref = "$1" if mode == "subdomain" else "$2"
    (wp_dir(inst) / ".htaccess").write_text(
        "# BEGIN WordPress Multisite — generated by ./sb\n"
        "RewriteEngine On\n"
        "RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]\n"
        "RewriteBase /\n"
        "RewriteRule ^index\\.php$ - [L]\n"
        f"RewriteRule ^{strip}wp-admin$ {'$1' if strip else ''}wp-admin/ [R=301,L]\n"
        "RewriteCond %{REQUEST_FILENAME} -f [OR]\n"
        "RewriteCond %{REQUEST_FILENAME} -d\n"
        "RewriteRule ^ - [L]\n"
        f"RewriteRule ^{strip}(wp-(content|admin|includes).*) {ref} [L]\n"
        f"RewriteRule ^{strip}(.*\\.php)$ {ref} [L]\n"
        "RewriteRule . index.php [L]\n"
        "# END WordPress Multisite\n"
    )


def _convert_multisite(inst: str, inst_cfg: dict) -> None:
    """Convert a freshly installed single site to multisite, per the project's
    `multisite` config. Idempotent: skips the convert when the network tables
    already exist. The marker file written here is what turns on the MULTISITE
    constants in WORDPRESS_CONFIG_EXTRA (see _config_extra_php) — wp-cli also
    writes them into wp-config.php, but the official entrypoint wipes that on
    the next container start."""
    mode = _multisite_mode(inst_cfg)
    if not mode:
        return
    chk = wpcli(["core", "is-installed", "--network"],
                instance=inst, check=False, capture=True)
    if chk.returncode != 0:
        info(f"converting to multisite ({mode})…")
        cmd = ["core", "multisite-convert"]
        if mode == "subdomain":
            cmd.append("--subdomains")
        # apache/nginx get the constants from WORDPRESS_CONFIG_EXTRA (marker-
        # gated) — letting wp-cli ALSO write them into wp-config.php would
        # double-define ("already defined" warnings on every request until the
        # next restart wipes the file). litespeed/herd are the opposite: no
        # container env reaches PHP there, so the literal constants wp-cli
        # writes are the only ones that work (and their wp-config is stable).
        if inst_cfg.get("server") not in ("litespeed", "herd"):
            cmd.append("--skip-config")
        wpcli(cmd, instance=inst)
    (wp_dir(inst) / MULTISITE_MARKER).write_text(
        "Generated by ./sb after `wp core multisite-convert`. Gates the\n"
        "MULTISITE constants in WORDPRESS_CONFIG_EXTRA — delete only if you\n"
        "want the instance to fall back to single-site mode.\n")
    _write_multisite_htaccess(inst, mode)
    if inst_cfg.get("server") == "litespeed":
        # OLS only re-reads the .htaccess on reload.
        compose("exec", "-T", "wp", "/usr/local/lsws/bin/lswsctrl", "restart",
                instance=inst, check=False)


def save_local_app_password(app_pw: str, instance: str) -> None:
    """Persist the WP Application Password into sandbox.local.yml so the
    MCP server picks it up on next launch.

    Written to `instances.<name>.app_password` so each instance has its own
    secret without colliding. (Per-project model — there is no global key.)
    """
    ensure_pyyaml()
    import yaml
    local = {}
    if CONFIG_LOCAL.exists():
        with CONFIG_LOCAL.open() as f:
            local = yaml.safe_load(f) or {}
    local.setdefault("instances", {}).setdefault(instance, {})["app_password"] = app_pw
    with CONFIG_LOCAL.open("w") as f:
        yaml.safe_dump(local, f, default_flow_style=False, sort_keys=False)


def save_local_abilities_enabled(enabled: bool, instance: str) -> None:
    """Mirror the abilities enable-flag into sandbox.local.yml (spec 003 T003).

    The WP option `sandbox_abilities_enabled` is the runtime source of truth, but
    it lives in the DB and is wiped by a recreate / db-reset. Mirroring the choice
    to `instances.<name>.abilities_enabled` makes it durable so `up` can re-apply
    it. Written via the same per-instance pattern as the other secrets."""
    ensure_pyyaml()
    import yaml
    local = {}
    if CONFIG_LOCAL.exists():
        with CONFIG_LOCAL.open() as f:
            local = yaml.safe_load(f) or {}
    local.setdefault("instances", {}).setdefault(instance, {})["abilities_enabled"] = bool(enabled)
    with CONFIG_LOCAL.open("w") as f:
        yaml.safe_dump(local, f, default_flow_style=False, sort_keys=False)


def read_local_abilities_enabled(instance: str):
    """Return the mirrored abilities enable-flag (bool) or None if unset."""
    if not CONFIG_LOCAL.exists():
        return None
    try:
        ensure_pyyaml()
        import yaml
        with CONFIG_LOCAL.open() as f:
            local = yaml.safe_load(f) or {}
        val = (local.get("instances", {}).get(instance, {}) or {}).get("abilities_enabled")
        return None if val is None else bool(val)
    except Exception:
        return None


def save_local_autologin_token(token: str, instance: str) -> None:
    """Persist the sandbox autologin token in sandbox.local.yml so it can be
    included in the ensure_instance return value as login_url."""
    ensure_pyyaml()
    import yaml
    local = {}
    if CONFIG_LOCAL.exists():
        with CONFIG_LOCAL.open() as f:
            local = yaml.safe_load(f) or {}
    local.setdefault("instances", {}).setdefault(instance, {})["autologin_token"] = token
    with CONFIG_LOCAL.open("w") as f:
        yaml.safe_dump(local, f, default_flow_style=False, sort_keys=False)


def _autologin_mu_plugin(token: str) -> str:
    """Render the autologin mu-plugin with the token embedded directly in the
    file. Storing the token here (not in wp-config.php) means it survives
    container restarts — the WordPress Docker entrypoint regenerates wp-config.php
    from env-vars on every start, wiping any constants we set via `wp config set`."""
    return f"""\
<?php
/**
 * Sandbox autologin — local dev only. Generated by ./sb; regenerated on recreate.
 * Visit /?sandbox_autologin=<token> to log in as admin without a password.
 * Token is in sandbox.local.yml (gitignored); never committed.
 */
// Token embedded in file so it survives wp-config.php regeneration on restart.
define( 'SANDBOX_AUTOLOGIN_TOKEN', '{token}' );

add_action( 'init', function () {{
    if ( empty( $_GET['sandbox_autologin'] ) ) {{
        return;
    }}
    if ( ! hash_equals( SANDBOX_AUTOLOGIN_TOKEN, (string) $_GET['sandbox_autologin'] ) ) {{
        return;
    }}
    $user = get_user_by( 'login', 'admin' );
    if ( $user ) {{
        wp_set_auth_cookie( $user->ID, true, is_ssl() );
        wp_safe_redirect( admin_url() );
        exit;
    }}
}}, 1 );
"""


def _force_symlink(link: Path, src: Path) -> None:
    """Replace whatever is at `link` with a symlink to `src`.

    `link.unlink()` fails with EPERM on a real (non-symlink) directory, which
    is exactly the state we hit when a wp.org install of the same slug already
    sits in the plugins folder. Detect that case and remove the directory tree
    instead. Symlinks (even dangling ones) get unlinked normally.
    """
    if link.is_symlink():
        link.unlink()
    elif link.is_dir():
        # Plain `rmtree` follows nothing here — link is a real dir, not a link.
        shutil.rmtree(link)
    elif link.exists():
        link.unlink()
    link.symlink_to(src)


def _active_project_name(instance: str) -> str | None:
    apf = active_project_file(instance)
    return apf.read_text().strip() if apf.exists() else None


def _relax_perms_for_uid_switch(inst: str) -> None:
    """Make the instance's WP files readable+writable across web-server uids.

    apache/nginx serve as www-data (uid 33); OpenLiteSpeed runs lsphp as uid
    1000. The WP files are the SAME bind-mounted host dir (runtime/wp-<inst>) —
    switching servers doesn't move data, but files written under one uid must
    stay readable (and uploads writable) under the other. The real fix for a
    bind-mounted dev tree is permissive group/other bits: a+rX everywhere, and
    a+rwX on the writable trees (uploads, cache, upgrade). No sudo, no chown —
    works whoever owns the files on the host."""
    root = wp_dir(inst)
    if not root.exists():
        return
    info(f"relaxing file perms on {root.name} so both web-server uids can read/write…")
    for p in root.rglob("*"):
        try:
            if p.is_dir():
                p.chmod(p.stat().st_mode | 0o055)        # a+rx on dirs
            else:
                p.chmod(p.stat().st_mode | 0o044)        # a+r on files
        except OSError:
            pass
    # The trees WP writes to at runtime need group/other write too.
    for sub in ("wp-content/uploads", "wp-content/cache", "wp-content/upgrade"):
        d = root / sub
        for p in [d, *d.rglob("*")] if d.exists() else []:
            try:
                p.chmod(p.stat().st_mode | (0o022 if p.is_dir() else 0o022))
            except OSError:
                pass


def _wire_project_plugins(name: str, root: str, pconf: dict) -> None:
    """Wire the project's plugins into the instance from the canonical resolved
    map (spec 010: `plugins_resolved` = {slug: {source, active, on_demand}}).

    Per entry: local path -> symlink under the SLUG KEY (worktree-safe); zip/org ->
    install; activate per state; on-demand -> NOT installed (its local source is
    registered into the local-source map the mu-plugin serves on install). Legacy
    non-plugin `mappings`/`mappings_inactive` (other wp-paths) are still handled
    here. NOTE: absolute symlinks only resolve inside the container when the target
    is under a bind-mounted host path (the extra_mounts collector handles that)."""
    pdir = plugins_dir(name)
    pdir.mkdir(parents=True, exist_ok=True)
    root_path = Path(root)
    wp_root = wp_dir(name)

    def _abs(val: str) -> Path:
        p = Path(str(val)).expanduser()
        return p if p.is_absolute() else (root_path / p).resolve()

    resolved = pconf.get("plugins_resolved")
    if not isinstance(resolved, dict):
        resolved = {}

    activate: list[str] = []            # slugs to activate (symlinked or present)
    org_install_active, org_install_inactive = [], []
    zip_install_active, zip_install_inactive = [], []
    local_sources: dict[str, dict] = {}  # slug -> {path|zip} for the mu-plugin

    for slug, e in resolved.items():
        src = e.get("source") or {"kind": "org", "value": None}
        kind = src.get("kind")
        if e.get("on_demand"):
            # Do NOT install now; register a LOCAL source so any later install
            # attempt (FSI / wp-cli / wp-admin) is served from local.
            if kind == "path":
                p = _abs(src["value"])
                if p.exists():
                    local_sources[slug] = {"path": str(p)}
            elif kind == "zip":
                local_sources[slug] = {"zip": src["value"]}
            continue  # org on-demand: nothing to register (WP pulls org on demand)
        if kind == "path":
            p = _abs(src["value"])
            if not p.exists():
                info(f"plugin '{slug}': local source not found at {p} — skipping "
                     f"(not falling back to org).")
                continue
            _force_symlink(pdir / slug, p)         # slug = map KEY (worktree-safe)
            local_sources[slug] = {"path": str(p)}  # also serve local on re-install
            if e.get("active"):
                activate.append(slug)
        elif kind == "zip":
            (zip_install_active if e.get("active") else zip_install_inactive).append(
                src["value"])
        else:  # org
            if (pdir / slug).exists():
                if e.get("active"):
                    activate.append(slug)
            else:
                (org_install_active if e.get("active") else org_install_inactive).append(
                    slug)

    # Legacy NON-plugin mappings (wp-paths that aren't wp-content/plugins/<slug>):
    # symlink as before. Plugin-path mappings were folded into plugins_resolved.
    for key in ("mappings", "mappings_inactive"):
        for wp_path, src in (pconf.get(key) or {}).items():
            parts = str(wp_path).strip("/").split("/")
            is_plugin = (len(parts) == 3 and parts[0] == "wp-content"
                         and parts[1] == "plugins")
            if is_plugin:
                continue  # handled via plugins_resolved
            src_p = _abs(src)
            if src_p.exists():
                dest = wp_root / str(wp_path)
                dest.parent.mkdir(parents=True, exist_ok=True)
                _force_symlink(dest, src_p)

    if org_install_active:
        wpcli(["plugin", "install", *org_install_active, "--activate"],
              instance=name, check=False)
    if org_install_inactive:
        wpcli(["plugin", "install", *org_install_inactive], instance=name, check=False)
    if zip_install_active:
        wpcli(["plugin", "install", *zip_install_active, "--activate"],
              instance=name, check=False)
    if zip_install_inactive:
        wpcli(["plugin", "install", *zip_install_inactive], instance=name, check=False)
    if activate:
        wpcli(["plugin", "activate", *activate], instance=name, check=False)

    _write_local_sources(name, local_sources)


def _pkg_slug(entry: str) -> str:
    """Best-effort slug from a plugin/theme entry: wp.org slug as-is; zip URL by
    basename minus the version tail (twentytwentyfour.1.5.zip →
    twentytwentyfour); local path by directory name."""
    if entry.startswith("http"):
        base = entry.rstrip("/").rsplit("/", 1)[-1]
        base = base[:-4] if base.endswith(".zip") else base
        return re.sub(r"\.\d[\d.]*$", "", base)
    if "/" in entry or entry.startswith((".", "~")):
        return Path(entry).expanduser().name
    return entry


def _wire_project_themes(name: str, root: str, pconf: dict) -> None:
    """Install the project's `themes` and activate the FIRST one. Same entry
    forms as plugins: wp.org slug, zip URL, or local path (symlinked in —
    needs an extra_mounts bind like plugin paths do). Activation is a
    separate explicit step: `theme install --activate` is silently ignored
    on multisite installs."""
    themes = [t for t in (pconf.get("themes") or []) if t and isinstance(t, str)]
    if not themes:
        return
    tdir = wp_dir(name) / "wp-content" / "themes"
    tdir.mkdir(parents=True, exist_ok=True)
    root_path = Path(root)
    for entry in themes:
        if entry.startswith("http") and entry.endswith(".zip"):
            if (tdir / _pkg_slug(entry)).exists():
                continue  # already present (bundled / prior provision) — skip noisy reinstall
            wpcli(["theme", "install", entry], instance=name, check=False)
        elif "/" in entry or entry.startswith((".", "~")):
            src = Path(entry).expanduser()
            if not src.is_absolute():
                src = (root_path / entry).resolve()
            if src.exists():
                _force_symlink(tdir / src.name, src)
        elif (tdir / _pkg_slug(entry)).exists():
            # Already present (e.g. a default theme bundled with WP core, or a
            # prior provision). Reinstalling only emits "Destination folder
            # already exists" + "Error: No themes installed." noise — skip it.
            continue
        else:
            wpcli(["theme", "install", entry], instance=name, check=False)
    wpcli(["theme", "activate", _pkg_slug(themes[0])],
          instance=name, check=False)
