"""Public typed foundation for instance-scoped server configuration."""

from .adapters.base import (
    AdapterDescriptor,
    AdapterRegistry,
    RenderedFile,
    RenderedGeneration,
    ServerConfigAdapter,
)
from .context import (
    Clock,
    InstanceRegistry,
    ProjectIdentityResolver,
    RepositoryFactory,
    ServerConfigDependencies,
    ServerConfigInstanceContext,
    ServerConfigMountProjection,
    SystemClock,
    project_instance_context,
    project_mount,
)
from .models import (
    ActivationTransaction,
    BehaviorEvidence,
    FragmentSet,
    InspectionState,
    InstanceConfigAuthority,
    InstanceIdentityProjection,
    KnownGoodReceipt,
    Operation,
    OperationResult,
    PhaseEvidence,
    PhaseResult,
    Readiness,
    RuntimeMode,
    RuntimeObservation,
    ServerConfigFragment,
    ServerType,
    TerminalOutcome,
    TransactionPhase,
    ValidationEvidence,
)
from .repository import ServerConfigRepository


__all__ = (
    "ActivationTransaction",
    "AdapterDescriptor",
    "AdapterRegistry",
    "BehaviorEvidence",
    "Clock",
    "FragmentSet",
    "InspectionState",
    "InstanceConfigAuthority",
    "InstanceIdentityProjection",
    "InstanceRegistry",
    "KnownGoodReceipt",
    "Operation",
    "OperationResult",
    "PhaseEvidence",
    "PhaseResult",
    "ProjectIdentityResolver",
    "Readiness",
    "RenderedFile",
    "RenderedGeneration",
    "RuntimeMode",
    "RuntimeObservation",
    "RepositoryFactory",
    "ServerConfigAdapter",
    "ServerConfigDependencies",
    "ServerConfigFragment",
    "ServerConfigInstanceContext",
    "ServerConfigMountProjection",
    "ServerConfigRepository",
    "ServerType",
    "SystemClock",
    "TerminalOutcome",
    "TransactionPhase",
    "ValidationEvidence",
    "project_instance_context",
    "project_mount",
)
