"""Application boundary for persistent and isolated workspace lifecycle."""

from __future__ import annotations

from typing import Protocol


class WorkspaceServiceProtocol(Protocol):
    def create(self, request): ...
    def list(self, request): ...
    def status(self, request): ...
    def reset(self, request): ...
    def destroy(self, request): ...
