#!/usr/bin/env bash
# Sandbox HTTPS-proxy helper — the ONLY privileged host actions the sandbox
# proxy needs (loopback alias + dnsmasq/resolver for the *.sb TLD).
#
# Deliberately tiny, argument-fixed, and strict so it's safe to allow via a
# scoped passwordless sudoers rule (see `./sb domains setup`). Each action is a
# single fixed command — there is nothing to inject. mkcert is NOT here: it's
# inherently interactive (writes to the login keychain) and runs as the user.
#
# Usage:
#   proxy-helper.sh alias-up      # ifconfig lo0 alias 127.0.0.77   (idempotent)
#   proxy-helper.sh alias-down    # ifconfig lo0 -alias 127.0.0.77
#   proxy-helper.sh dns-up        # write *.sb -> 127.0.0.77 (dnsmasq + resolver)
#   proxy-helper.sh dns-down      # remove the dnsmasq + resolver entries
set -euo pipefail

ALIAS_IP=127.0.0.77
BREW_PREFIX="${HOMEBREW_PREFIX:-/opt/homebrew}"
DNSMASQ_CONF="$BREW_PREFIX/etc/dnsmasq.d/sandbox-sb.conf"
RESOLVER=/etc/resolver/sb

restart_dnsmasq() {
  # Prefer the brew service; fall back to launchd kickstart. Best-effort.
  if command -v brew >/dev/null 2>&1; then
    brew services restart dnsmasq >/dev/null 2>&1 && return 0
  fi
  launchctl kickstart -k "system/$(ls /Library/LaunchDaemons 2>/dev/null \
    | grep -i dnsmasq | head -1 | sed 's/\.plist$//')" 2>/dev/null || true
}

action="${1:-}"
case "$action" in
  alias-up)
    # Idempotent: adding an existing alias is a no-op that returns 0.
    ifconfig lo0 alias "$ALIAS_IP" up
    ;;
  alias-down)
    ifconfig lo0 -alias "$ALIAS_IP" 2>/dev/null || true
    ;;
  dns-up)
    mkdir -p "$(dirname "$DNSMASQ_CONF")"
    printf '# Generated by ./sb — sandbox *.sb TLD. Safe to delete.\naddress=/.sb/%s\n' \
      "$ALIAS_IP" > "$DNSMASQ_CONF"
    mkdir -p /etc/resolver
    printf 'nameserver 127.0.0.1\n' > "$RESOLVER"
    restart_dnsmasq
    ;;
  dns-down)
    rm -f "$DNSMASQ_CONF" "$RESOLVER"
    restart_dnsmasq
    ;;
  *)
    echo "proxy-helper: unknown action '$action'" >&2
    echo "usage: proxy-helper.sh alias-up|alias-down|dns-up|dns-down" >&2
    exit 2
    ;;
esac
echo "proxy-helper: $action ok"
