#!/usr/bin/env bash
# Sandbox HTTPS-proxy helper — the ONLY privileged host actions the sandbox
# proxy needs (loopback alias + dnsmasq/resolver for the *.tst TLD).
#
# Deliberately tiny, argument-fixed, and strict so it's safe to allow via a
# scoped passwordless sudoers rule (see `./sb domains setup`). Each action is a
# single fixed command — there is nothing to inject. mkcert is NOT here: it's
# inherently interactive (writes to the login keychain) and runs as the user.
#
# Usage:
#   proxy-helper.sh alias-up      # ifconfig lo0 alias 127.0.0.77   (idempotent)
#   proxy-helper.sh alias-down    # ifconfig lo0 -alias 127.0.0.77
#   proxy-helper.sh dns-up <tld>  # write *.<tld> -> 127.0.0.77 (dnsmasq + resolver)
#   proxy-helper.sh dns-down <tld># remove that TLD's dnsmasq + resolver entries
set -euo pipefail

ALIAS_IP=127.0.0.77
BREW_PREFIX="${HOMEBREW_PREFIX:-/opt/homebrew}"
# Local sandbox TLD — passed as $2 by `sb` (from sandbox.config.json `tld`,
# default `tst`). Each TLD gets its own resolver + dnsmasq file, so several can
# coexist. We avoid `.sb` (a real ccTLD) and `.test` (owned by Herd/Valet).
TLD="${2:-tst}"
DNSMASQ_CONF="$BREW_PREFIX/etc/dnsmasq.d/sandbox-$TLD.conf"
RESOLVER=/etc/resolver/$TLD

reload_dnsmasq() {
  # Reload the RUNNING dnsmasq + clear its cache, however it's managed. We've
  # seen dnsmasq be Valet-run (root, NOT brew-managed), so `brew services
  # restart` silently no-ops and a stale cached record (e.g. xspeed.tst pointing
  # at an old IP) shadows the wildcard. So: SIGHUP every live dnsmasq by PID
  # (clears cache + re-reads config — works regardless of manager), and also
  # try brew/launchd as a belt-and-suspenders. All best-effort.
  local pids
  pids="$(pgrep dnsmasq 2>/dev/null || true)"
  if [ -n "$pids" ]; then
    # shellcheck disable=SC2086
    kill -HUP $pids 2>/dev/null || true
  fi
  command -v brew >/dev/null 2>&1 && brew services restart dnsmasq >/dev/null 2>&1 || true
}

flush_macos_dns() {
  # Drop macOS's own resolver cache so it re-queries dnsmasq for *.tst names.
  dscacheutil -flushcache 2>/dev/null || true
  killall -HUP mDNSResponder 2>/dev/null || true
}

action="${1:-}"
case "$action" in
  alias-up)
    # Idempotent: adding an existing alias is a no-op that returns 0.
    ifconfig lo0 alias "$ALIAS_IP" up
    ;;
  alias-down)
    ifconfig lo0 -alias "$ALIAS_IP" 2>/dev/null || true
    ;;
  dns-up)
    mkdir -p "$(dirname "$DNSMASQ_CONF")"
    printf '# Generated by ./sb — sandbox *.%s TLD. Safe to delete.\naddress=/.%s/%s\n' \
      "$TLD" "$TLD" "$ALIAS_IP" > "$DNSMASQ_CONF"
    mkdir -p /etc/resolver
    printf 'nameserver 127.0.0.1\n' > "$RESOLVER"
    reload_dnsmasq
    flush_macos_dns
    ;;
  dns-down)
    rm -f "$DNSMASQ_CONF" "$RESOLVER"
    reload_dnsmasq
    flush_macos_dns
    ;;
  dns-flush)
    # Self-heal: reload dnsmasq (drop stale cached *.tst records) + flush macOS
    # cache. Called automatically by `sb` after any domain change, so the user
    # never has to run a terminal command to fix resolution.
    reload_dnsmasq
    flush_macos_dns
    ;;
  *)
    echo "proxy-helper: unknown action '$action'" >&2
    echo "usage: proxy-helper.sh alias-up|alias-down|dns-up|dns-down|dns-flush" >&2
    exit 2
    ;;
esac
echo "proxy-helper: $action ok"
